baseURL: "https://carson-anderson.com"
languageCode: "en-us"
title: "Carson Anderson"
theme: hugo-profile

Paginate: 5
# disqusShortname: gurusabarish
googleAnalytics: G-CVENSN9X26

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: talks
      name: Talks
      title: Talks
      url: /talks
      weight: 1

params:
  title: Carson Anderson
  description: A personal landing page for Carson Anderson
  favicon: "/images/me-clean.png"

  theme:
    disableThemeToggle: true
    defaultTheme: dark

  # If you want to customize the menu, you can change it here
  navbar:
    align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/images/me-pixel.png" # Logo for the brand | default is the favicon variable

    menus:
      # disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: false
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    title: "Carson Anderson"
    subtitle: ""
    content: "An experienced engineer with a passion for Automation, Scale, and Maintainability"
    image: /images/icon.jpeg
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/carsonoid
        - icon: fab fa-twitter
          url: https://twitter.com/carson_ops

  # About
  about:
    enable: true
    title: "About Me"
    # image: "/images/me.png"
    content: |-
      I love to teach others and work hard to truly understand the technology I use.
    skills:
      enable: true
      title: "I am currently passionate about and exploring the following new technologies"
      items:
        - Go
        - GCP
        - Kubernetes
        - Github Actions

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/carsonoid
      linkedin: https://www.linkedin.com/in/carsonoid/
      twitter: https://twitter.com/carson_ops
